name = "SMIOL"
version = "0.1.0"
license = "license"
author = "luflarois"
maintainer = "luflarois@gmail.com"
copyright = "Copyright 2024, luflarois"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-external=true
implicit-typing=true
source-form = "free"
[dependencies]
mpi = "*"
openmp = "*"

